version: '3.1'

services:
  nginx:
    hostname: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ecommerce

  ecommerce:
    hostname: ecommerce-app
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: ${PROJECT_NAME}-php
    volumes:
      - ./:/var/www/app
    command: sh -c 'php-fpm'

  mariadb:
#    image: mariadb:10.3
    image: mariadb:latest
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty123
    ports:
      - "3306:3306"
    restart: on-failure